**Step 1: Importing the libraries**

In [93]:
import numpy as np
import pandas as pd

**Step 2: Importing dataset**

In [94]:
dataset = pd.read_csv("../../datasets/day-06-data.csv")

#All rows all columns except last (target)
X = dataset.iloc[:,:-1].values

#All rows but only one column (target)
Y = dataset.iloc[:,-1].values

In [95]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [96]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [97]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Step 3: Handling the missing data**

In [98]:
from sklearn.impute import SimpleImputer

#Lets replace the missing values with the mean of column
imputer = SimpleImputer(missing_values = np.nan,
                        strategy = "mean")

#All rows to be considered for mean, and only column 1 and 2 as they have missing values
X[:,1:3] = imputer.fit_transform(X[:,1:3])


In [99]:
#As you can see the NaN now replaced with mean of the column
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**Step 4: Encoding categorical data**

In [100]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[
        ("encoder", OneHotEncoder(), [0])
    ],
    remainder="passthrough"
)

X = np.array(ct.fit_transform(X))

In [101]:
from sklearn.preprocessing import LabelEncoder

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)


In [102]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [103]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


**Step 5: Splitting the datasets into training sets and Test sets**

In [104]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

**Step 6: Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

#Fit scalar only on training data
#Use the same scaling on test data
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)