In [20]:
import numpy as np

Use the printoptions supress so that numpy prints the output normally instead of scientifically in any e^x format

In [21]:
np.set_printoptions(suppress = True)

**DOT PRODUCTS**

In [22]:
v1 = np.array([1,3])
v2 = np.array([4,2])


In [23]:
dot = np.dot(v1,v2)
print(dot)

10


**Euclidean Distance**

In [24]:
diff = v1-v2
print(diff)

[-3  1]


linalg = linear algebra

norm = euclidean distance

In [25]:
distance = np.linalg.norm(diff)
print(distance)

3.1622776601683795


**Matrix Multiplication and Linear Model**

In [26]:
X = np.array([
    [1.0, 30.0],
    [2.0, 50.0],
    [3.0, 70.0]
])

print("X:\n", X)
print("X shape: ",X.shape)

X:
 [[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]
X shape:  (3, 2)


In [27]:
W = np.array([
    [0.5],
    [0.1]
])

print("W:\n", W)
print("W shape: ",W.shape)

W:
 [[0.5]
 [0.1]]
W shape:  (2, 1)


  X       W

(3,2) * (2,1)
   
   2 and 2

These two should be same

and result will be of shape (3,1)

In [28]:
xw = X @ W  #np.dot() = @ 
#both do matrix multiplication just @ is easy 
print(xw)
print(xw.shape)

[[3.5]
 [6. ]
 [8.5]]
(3, 1)


**y = XW + b**

In [29]:
b = 2.0

y = xw +b
print(y)
print(y.shape)

[[ 5.5]
 [ 8. ]
 [10.5]]
(3, 1)


In [30]:
print(X)
#here the 2 columns represent 2 features

[[ 1. 30.]
 [ 2. 50.]
 [ 3. 70.]]


In [31]:
print(W)
#First weight is for 1st feature and 2nd for 2nd feature

[[0.5]
 [0.1]]


**Connecting this to a samples dataset**

In [32]:
data = np.array([
    [85,26.6,31,0],
    [183,23.3,32,1],
    [89,28.1,21,0],
    [137,43.1,33,1]
])
print(data)
print(data.shape)

[[ 85.   26.6  31.    0. ]
 [183.   23.3  32.    1. ]
 [ 89.   28.1  21.    0. ]
 [137.   43.1  33.    1. ]]
(4, 4)


In [33]:
X_features = data[:,:-1] #all rows all columns (except last)
X_target = data[:,-1] #all rows but only last column


print(X_features)
print(X_features.shape)


print("\n\n",X_target)
print(X_target.shape)

[[ 85.   26.6  31. ]
 [183.   23.3  32. ]
 [ 89.   28.1  21. ]
 [137.   43.1  33. ]]
(4, 3)


 [0. 1. 0. 1.]
(4,)


In [34]:
#Transpose of a Matrix

A = np.array([
    [1,2],
    [3,4]
])

print(A.T)

# Rows become columns and columns become rows

[[1 3]
 [2 4]]
