In [1]:
import numpy as np

In [3]:
np.set_printoptions(suppress = True) #Cleaner printing for Scientific notations

**1.Scalar, Vector, Matrices & Tensor in Numpy**

In [5]:
#scalar - single number
scalar = 5.0
print(scalar)

5.0


In [7]:
#vector - 1D data
vector = np.array(
    [3,7,2]
)
print(vector, vector.shape)

[3 7 2] (3,)


In [8]:
#Matrix - 2D data (row,col)

matrix = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [10]:
#Tensor - 3D data

tensor = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [11,12,13],
            [14,15,16]
        ]
    ]
)

print(tensor)
print(tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
(2, 2, 3)
