In [71]:
import numpy as np


In [72]:
np.__version__

'2.4.4'

In [73]:
import time

n = 1_000_000

start = time.time()
py_list = [i * 2 for i in range(n)]
print("Python time:", time.time() - start)

start = time.time()
np_array = np.arange(n) * 2
print("NumPy time:", time.time() - start)



Python time: 0.09086871147155762
NumPy time: 0.002151966094970703


In [74]:
arr1 = np.array([1,2,3,4,5])
print(type(arr1))

print("1D array : ", arr1)

<class 'numpy.ndarray'>
1D array :  [1 2 3 4 5]


In [75]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

(5,)
1
5


In [76]:
arr2 = np.array([[1,2,3],[4,5,6],[23,24,56]])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 56]])

In [77]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

(3, 3)
2
9


**Creating Special Arrays**

In [78]:
zeroes = np.zeros((3,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [80]:
random = np.random.rand(3,3)
random

array([[0.1126667 , 0.25543202, 0.78953688],
       [0.1582826 , 0.52914126, 0.78455614],
       [0.89078165, 0.86270563, 0.71578766]])

In [81]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr[2,1])
print(arr[1])
print(arr[:,1])

8
[4 5 6]
[2 5 8]


**Array Operations**


In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition: ", a+b)
print("Subtraction: ",a-b)
print("Multiplication: ", a*b)
print("Division: ", a/b)
print("Dot product: ", np.dot(a,b))
print("Cross product: ", np.cross(a,b))

Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Dot product:  32
Cross product:  [-3  6 -3]


**Reshaping and Flatenning**

In [83]:
arr = np.arange(1,10)
reshaped = arr.reshape(3,3)
flattened = reshaped.flatten()
print(reshaped)
print(flattened)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [84]:
arr = np.array([1,2,1,2,1])
print(np.sum(arr == 1))

3


**Broadcasting** - Vectorization

In [85]:
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


**Statistics**

In [86]:
arr = np.array([10,20,30,40,50])

print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

30.0
150
50
10


**Boolean Masking** - filtering the data

In [87]:
arr = np.array([10,20,30,40,50])

print(arr[arr > 25])

[30 40 50]


In [88]:
arr = np.array([10,20,30,40,50])

mean = np.mean(arr)
above_mean = arr[arr > mean]

print("Mean:", mean)
print("Above mean:", above_mean)

Mean: 30.0
Above mean: [40 50]
